#!/bin/bash
#VARs
GUI_USER=`users | awk '{print $1}'`
EXEC_USR=`whoami`
EMPTY_ENV=1
CRASH_ENV=0
FIRST_RUN=1
SELF=`readlink -f $0`
RUN_TYPE=
PRIVILEGE=

#DIRs
WORK_DIR=.autopoweroff
HOME_DIR=/home/"$GUI_USER"
if [ "$GUI_USER" = "root" ];then
    HOME_DIR=/root/
fi
WORK_PATH=$HOME_DIR/$WORK_DIR
CONF_PATH=$WORK_PATH/conf
LOG_PATH=$WORK_PATH/logs
SESSION_PATH=$WORK_PATH/sessions
BIN_PATH=$WORK_PATH/bin

#FILEs
CONF_FILE=$CONF_PATH/poweroff.conf
BIN_FILE=$BIN_PATH/autopoweroff
SESSION_FILE=
LOG_FILE=

#FUNCs
is_digit() {
    if grep '^[[:digit:]]*$' <<< $1;then
        return 1
    else
        return 0
    fi
}

function_env_check() {
    if [ ! -d $WORK_PATH ];then
        return 1
    fi
    return 0
}

function_create_env() {
    mkdir -p $WORK_PATH
    mkdir -p $CONF_PATH
    mkdir -p $SESSION_PATH
    mkdir -p $BIN_PATH
    mkdir -p $LOG_PATH
    touch $CONF_FILE
    chown $GUI_USER:$GUI_USER -R $WORK_PATH
}

function_conf_get() {
    key=$1
    file=$2
    if [ -f $CONF_FILE ];then
        value=`awk -F'=' '/^'$key'=/{print $2}' $file`
    else
        value=""
    fi
    echo $value
}

function_conf_set() {
    key=$1
    value=$2
    file=$3
    sed -i -e '/^'${key}'=/d'  $file
    echo $key=$value >> $file
}

function_func_selection(){
    zenity --list \
    --radiolist \
    --title="选择" \
    --text="" \
    --column='选  择' --column='id' --column='使用的方式' --hide-column=2 \
    TRUE 'reboot' '重启' FALSE 'poweroff' '关机'  FALSE 'export' '导出历史日志'\
    --width=280  --height=300
}

function_cancel() {
    zenity --error --text="用户取消操作！"
    exit
}

function_not_support() {
    zenity --error --text=" 工具不支持该系统！"
    exit
}

function_time_selection(){
    TIME_TMP=$(zenity --list \
    --radiolist \
    --title="选择" \
    --text="选择时间设定：" \
    --column='选  择' --column='设定时间' --column='tag' --print-column=3 \
    TRUE '15s' '15' FALSE '30s' '30' FALSE '自定义' 'else'\
    --width=280  --height=300 --hide-column=3)
    if [ "$TIME_TMP" == "else" ];then
        TIME_TMP=$(zenity --entry --title="自定义时间" --text="时间以s为单位" --entry-text="请输入时间(s)")
    fi
    echo $TIME_TMP
}

function_su_check() {
    sh -c "sleep 0.5; echo $PASSWD" | script -qc "su - $USER; su -c 'echo OK'" | tail -n 1
}

SUDOFILE=/etc/sudoers
function_remove_sudo_password() {
    #must root
    echo "$GUI_USER ALL=(ALL:ALL) NOPASSWD:ALL #autopoweroff_commit" >>$SUDOFILE
}

function_restore_sudo_password() {
    #admin user
    sudo sed -i '/autopoweroff_commit/d' /etc/sudoers
}

function_restore_sudo() {
    usr=$1
    PRIVILEGE=$(function_conf_get "PRIVILEGE" $CONF_FILE)
    if [ "$PRIVILEGE" == "su" ];then
        gpasswd -d $usr sudo
    fi
}

function_add_sudo() {
    usr=$1
    PRIVILEGE=$(function_conf_get "PRIVILEGE" $CONF_FILE)
    if [ "$PRIVILEGE" == "su" ];then
        gpasswd -a $usr sudo
    fi
}

function_check_sudo_priv() {
    #sudo_check=`groups $GUI_USER | grep sudo | wc -l`
    #do not use groups to check the privilege, you won't
    #know it, if you just add the user to one group without logout.
    check_user=$1
    users=`cat /etc/group | grep "^sudo\:" | cut -d ":" -f 4`
    OLDIFS=$IFS
    IFS=","
    user_array=($users)
    for user in ${user_array[@]}
    do
        if [ "$check_user" == "$user" ];then
            return 0
        fi
    done
    return 1
}

function_switch_to_root() {
    if [ "$EXEC_USR" != "root" ];then
        sudo_password=`zenity --password --title="输入sudo密码以运行程序"`
        if [ ! -n "$sudo_password" ];then
            function_cancel
        fi
        sudo -k
        echo "$sudo_password" | sudo -S bash -c "exit" >/dev/null 2>&1
        check=$?
        if [ "$check" != "0" ];then
            zenity --error --text="无法提升权限，可能由以下原因造成。\n1、密码错误，请重新输入密码。\n2、用户无sudo权限，通过su切换到root运行脚本!"
            exit
        else
            echo "$sudo_password" | sudo -E -S bash -c "$SELF"
        fi
        exit
    fi
}

function_stop_run() {
    function_conf_set "RUNNING_STAT" "STOP" $CONF_FILE
    function_restore_login
    #function_restore_sudo $GUI_USER
    function_restore_sudo_password
    function_cancel_autostart
    function_export_to_directory
    exit
}

function_show_count_down() {
    COUNT_DOWN=$1
    TOTAL_COUNT=$2
    {
        while [ "$COUNT_DOWN" != "0" ];
        do
            echo "#$RUN_TYPE in $COUNT_DOWN seconds"
            let COUNT_DOWN=$COUNT_DOWN-1
            sleep 1
        done
    }|zenity --progress --title="第${TOTAL_COUNT}次执行"  --pulsate --cancel-label="停止执行并导出日志" --ok-label="请等待" --auto-close
    if [ "$?" == "1" ];then
        function_stop_run
    fi
}

function_gen_uuid() {
    cat /proc/sys/kernel/random/uuid
}

function_is_lightdm() {
    LIGHTDM_RUNNING=`ps aux | grep lightdm | wc -l`
    if [ "$LIGHTDM_RUNNING" -lt "1" ];then
        return 1
    else
        return 0
    fi
}

function_is_gdm3() {
    GDM_RUNNING=`ps aux | grep gdm3 | wc -l`
    if [ "$GDM_RUNNING" -lt "1" ];then
        return 1
    else
        return 0
    fi
}

DISPLAY_MANAGER_FILE=/etc/X11/default-display-manager
function_desktop_env() {
    if [ -f $DISPLAY_MANAGER_FILE ];then
        basename $(cat ${DISPLAY_MANAGER_FILE})
        return 0
    fi
    if [ function_is_lightdm ];then
        echo "lightdm"
        return 0
    fi
    if [ function_is_gdm3 ];then
        echo "gdm3"
        return 0
    fi
    echo "unknow desktop"
}

LIGHTDM_CONF_FILE="/etc/lightdm/lightdm.conf.d/removelogin.conf"
LIGHTDM_CONF_PATH="/etc/lightdm/lightdm.conf.d/"
function_remove_lightdm_login() {
    if [ ! -d $LIGHTDM_CONF_PATH ];then
        mkdir -p $LIGHTDM_CONF_PATH
    fi
    touch $LIGHTDM_CONF_FILE
    chown root:root $LIGHTDM_CONF_FILE
    echo "[SeatDefaults]" >$LIGHTDM_CONF_FILE
    echo "autologin-user="$GUI_USER >>$LIGHTDM_CONF_FILE
}

GDM3_CONF_FILE="/etc/gdm3/custom.conf"
function_remove_gdm3_login() {
    SESSION_ID=$(function_conf_get "SESSION_NAME" $CONF_FILE)
    GDM3_CONF_FILE_BACKUP=$CONF_PATH/${SESSION_ID}_custom.conf
    if [ -f $GDM3_CONF_FILE ];then
        function_conf_set "DESKTOP_ENV_CONF_BKUP" $GDM3_CONF_FILE_BACKUP $CONF_FILE 
        chown $GUI_USER:$GUI_USER $GDM3_CONF_FILE
        cp $GDM3_CONF_FILE $GDM3_CONF_FILE_BACKUP
        chown $GUI_USER:$GUI_USER $GDM3_CONF_FILE_BACKUP
        echo "[daemon]" > $GDM3_CONF_FILE
        echo "AutomaticLoginEnable=True" >> $GDM3_CONF_FILE
        echo "AutomaticLogin="$GUI_USER >> $GDM3_CONF_FILE
    else
        function_conf_set "DESKTOP_ENV_CONF_BKUP" "NULL" $CONF_FILE 
        touch $GDM3_CONF_FILE
        chown root:root $GDM3_CONF_FILE
        echo "[daemon]" > $GDM3_CONF_FILE
        echo "AutomaticLoginEnable=True" >> $GDM3_CONF_FILE
        echo "AutomaticLogin="$GUI_USER >> $GDM3_CONF_FILE
    fi
}

function_remove_login() {
    case $DESKTOP_ENV in
    "lightdm")
        function_remove_lightdm_login
    ;;
    "gdm3")
        function_remove_gdm3_login
    ;;
    *)
        function_not_support
    ;;
    esac
}

function_restore_lightdm_login() {
    sudo rm $LIGHTDM_CONF_FILE
}

function_restore_gdm3_login() {
    GDM3_CONF_FILE_BACKUP=$(function_conf_get "DESKTOP_ENV_CONF_BKUP" $CONF_FILE)
    if [ "$GDM3_CONF_FILE_BACKUP" == "NULL" ];then
        sudo rm $GDM3_CONF_FILE
    else
        sudo mv $GDM3_CONF_FILE_BACKUP $GDM3_CONF_FILE
    fi
}

function_restore_login() {
    case $DESKTOP_ENV in
    "lightdm")
        function_restore_lightdm_login
    ;;
    "gdm3")
        function_restore_gdm3_login
    ;;
    *)
        function_not_support
    ;;
    esac
}

AUTOSTART_PATH=$HOME_DIR/.config/autostart
AUTOSTART_CONF=$AUTOSTART_PATH/poweroff.desktop
function_lightdm_autostart() {
    mkdir -p $AUTOSTART_PATH
    echo "[Desktop Entry]" >$AUTOSTART_CONF
    echo "Type=Application" >>$AUTOSTART_CONF
    echo "Exec="$BIN_FILE >>$AUTOSTART_CONF
    echo "Hidden=false" >>$AUTOSTART_CONF
    echo "Name[zh_CN]=autopoweroff" >>$AUTOSTART_CONF
    echo "Name=autopoweroff" >>$AUTOSTART_CONF
    chown -R  $GUI_USER:$GUI_USER $AUTOSTART_PATH
}

function_lightdm_cancel_autostart() {
    rm -f $AUTOSTART_CONF
}

function_gdm3_autostart() {
    function_lightdm_autostart
}

function_gdm3_cancel_autostart() {
    function_lightdm_cancel_autostart
}

function_autostart() {
    case $DESKTOP_ENV in
    "lightdm")
        function_lightdm_autostart
    ;;
    "gdm3")
        function_gdm3_autostart
    ;;
    *)
        function_not_support
    ;;
    esac

}

function_cancel_autostart() {
    case $DESKTOP_ENV in
    "lightdm")
        function_lightdm_cancel_autostart
    ;;
    "gdm3")
        function_gdm3_cancel_autostart
    ;;
    *)
        function_not_support
    ;;
    esac

}

function_copy_myself() {
    cp $SELF $BIN_FILE
    chown $GUI_USER:$GUI_USER $BIN_FILE
    chmod 755 $BIN_FILE
}

function_create_session() {
    SESSION_ID=`function_conf_get "SESSION_NAME" $CONF_FILE`
    SESSION_FILE=$SESSION_PATH/$SESSION_ID
    touch $SESSION_FILE
    chown $GUI_USER:$GUI_USER $SESSION_FILE
}

function_conf_write_down() {
    SESSION_UUID=`function_gen_uuid`
    DATE_STR=`date +%Y%m%d%H%M%S`
    function_conf_set "RUNNING_STAT" "RUNNING" $CONF_FILE
    function_conf_set "SESSION_NAME" "${DATE_STR}_${SESSION_UUID}" $CONF_FILE
    function_remove_login
    function_copy_myself
    function_autostart
}

function_init_session() {
    _RUN_TYPE=$1
    _RUN_TIME=$2
    function_create_session
    function_conf_set "RUN_TYPE" $_RUN_TYPE $SESSION_FILE
    function_conf_set "RUN_TIME" $_RUN_TIME $SESSION_FILE
    function_conf_set "TOTAL_COUNT" "0" $SESSION_FILE
}

function_init_logfile() {
    SESSION_ID=`function_conf_get "SESSION_NAME" $CONF_FILE`
    LOG_FILE=$LOG_PATH/$SESSION_ID.log
    function_conf_set "LOG_FILE" $LOG_FILE $CONF_FILE
    touch $LOG_FILE
    chown $GUI_USER:$GUI_USER $LOG_FILE
}

function_log_down() {
    LOG_FILE=`function_conf_get "LOG_FILE" $CONF_FILE`
    chelsio_num=`lspci | grep Chelsio | wc -l`
    pci_num=`lspci | wc -l`
    ETH_82574=`lspci | grep 82574L | wc -l`
    I350=`lspci | grep I350 | wc -l`
    IDT=`lspci | grep IDT | wc -l`
    VGA=`lspci | grep VGA | wc -l`
    Xilinx=`lspci | grep Xilinx | wc -l`
    str="pcisum=$pci_num chelsio=$chelsio_num IDT=$IDT 82574=$ETH_82574 I350=$I350 VGA=$VGA Xilinx=$Xilinx"
    DATE=`date "+%Y%m%d-%H%M"`
    echo $DATE $str >> $LOG_FILE
}

function_do_take_action() {
    ACTION=$1
    case $ACTION in
    "reboot")
        reboot
    ;;
    "poweroff")
        poweroff
    ;;
    *)
        zenity --error --text="未知操作 $ACTION"
    ;;
    esac
}

function_take_action() {
    SESSION_ID=`function_conf_get "SESSION_NAME" $CONF_FILE`
    SESSION_FILE=$SESSION_PATH/$SESSION_ID
    RUN_TYPE=`function_conf_get RUN_TYPE $SESSION_FILE`
    RUN_TIME=`function_conf_get RUN_TIME $SESSION_FILE`
    TOTAL_COUNT=`function_conf_get TOTAL_COUNT $SESSION_FILE`
    TOTAL_COUNT=`expr $TOTAL_COUNT + 1`
    function_conf_set "TOTAL_COUNT" $TOTAL_COUNT $SESSION_FILE
    function_remove_sudo_password
    function_log_down
    function_show_count_down $RUN_TIME $TOTAL_COUNT
    function_do_take_action $RUN_TYPE
}

function_export_to_directory() {
    LOG_FILE=`function_conf_get "LOG_FILE" $CONF_FILE`
    directory=`zenity --file-selection --title="导出日志到目录..." --directory`
    if [ "$?" == "0" ];then
        cp -a $LOG_FILE $directory
    else
        function_cancel
    fi
}

function_export_files_to_directory() {
    files=`zenity --file-selection --title="选择日志" --multiple --separator=" " --filename="$LOG_PATH/"`
    if [ "$?" ==  "0" ];then
        directory=`zenity --file-selection --title="导出日志到目录..." --directory`
        if [ "$?" == "0" ];then
            cp -a $files $directory
        else
            function_cancel
        fi
    else
        function_cancel
    fi
}

function_first_run() {
    if [ $EMPTY_ENV ];then
        function_create_env
    fi
    #BE CAREFUL WHEN ADD MORE ACTION BEFORE THIS
    function_switch_to_root
    RUN_TYPE=`function_func_selection`
    case $RUN_TYPE in
        "poweroff"|"reboot")
            RUN_TIME=`function_time_selection`
            if [ ! $(is_digit $RUN_TIME) ] || [ "$RUN_TIME" -lt "1" ];then
                zenity --error --text="输入时间错误！"
                exit
            fi
            function_conf_write_down
            function_init_session $RUN_TYPE $RUN_TIME
            function_init_logfile
            function_take_action
        ;;
        "export")
            function_export_files_to_directory
        ;;
        *)
            function_cancel
        ;;
    esac
}

###############################Start##################################
function_env_check
EMPTY_ENV=$?

if [ $EMPTY_ENV == 1 ];then
    FIRST_RUN=1
else
    running_stat=`function_conf_get "RUNNING_STAT" $CONF_FILE`
    if [ "$running_stat" == "RUNNING" ];then
        FIRST_RUN=0
    else
        FIRST_RUN=1
    fi
fi
DESKTOP_ENV=`function_desktop_env`
if [ "$FIRST_RUN" == "1" ];then
    function_first_run
else
    function_take_action
fi
#######finish no more############
